'use strict';
(()=>{
const base='https://qcscbkzpfvrbmtvhubtg.supabase.co';
const key='sb_publishable_qKdJB3Kch41AtT5-AI73Mg_0MJyateY';
const $=s=>document.querySelector(s), status=$('#account-status');
let session;try{session=JSON.parse(sessionStorage.getItem('bryanMember'))}catch{}
const hash=new URLSearchParams(location.hash.slice(1));
if(hash.get('access_token')){session={token:hash.get('access_token'),refresh:hash.get('refresh_token'),expires:Date.now()+Number(hash.get('expires_in')||3600)*1000};sessionStorage.setItem('bryanMember',JSON.stringify(session));history.replaceState(null,'',location.pathname)}
if(hash.get('error_description'))status.textContent=hash.get('error_description');
async function api(path,body,token){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Error(data.msg||data.message||data.error_description||'Unable to connect. Please try again.');return data}
const tiers=[{percent:25,cost:10000,limit:'Any job size'},{percent:50,cost:25000,limit:'Up to two truckloads'},{percent:75,cost:40000,limit:'Up to one full truck'}];
function list(selector,rows,empty,format){const root=$(selector);root.replaceChildren();if(!rows.length){const p=document.createElement('p');p.textContent=empty;root.append(p)}else rows.forEach(row=>{const p=document.createElement('p');p.className='member-row';p.textContent=format(row);root.append(p)})}
async function dashboard(){try{if(session.refresh&&session.expires<Date.now()+30000){const renewed=await api('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh});session={token:renewed.access_token,refresh:renewed.refresh_token,expires:Date.now()+renewed.expires_in*1000};sessionStorage.setItem('bryanMember',JSON.stringify(session))}const user=await api('/auth/v1/user',undefined,session.token);const data=await api('/rest/v1/rpc/customer_dashboard',{},session.token);$('#signin-panel').hidden=true;$('#member-panel').hidden=false;$('.reward-explainer').hidden=true;$('#member-identity').textContent=user.email;const balance=Math.max(0,Number(data.balance));$('#points-total').textContent=balance.toLocaleString()+' points';const next=tiers.find(t=>balance<t.cost)||tiers[2];$('#reward-progress').max=next.cost;$('#reward-progress').value=Math.min(balance,next.cost);$('#next-reward').textContent=balance>=40000?'All reward levels are unlocked.':(next.cost-balance).toLocaleString()+' points until '+next.percent+'% off';$('#reward-cards').replaceChildren();const pending=data.requests.some(r=>r.status==='pending');tiers.forEach(t=>{const card=document.createElement('article');card.className='panel';const title=document.createElement('h3');title.textContent=t.percent+'% off';const desc=document.createElement('p');desc.textContent=t.cost.toLocaleString()+' points · '+t.limit;const button=document.createElement('button');button.className='button';button.textContent=pending?'Request pending':balance>=t.cost?'Request reward':'Keep earning';button.disabled=pending||balance<t.cost;button.addEventListener('click',async()=>{button.disabled=true;try{await api('/rest/v1/rpc/request_reward',{reward_tier:t.percent},session.token);status.textContent='Request received. We’ll review eligibility before deducting any points.';await dashboard()}catch(e){status.textContent=e.message;button.disabled=false}});card.append(title,desc,button);$('#reward-cards').append(card)});list('#pickup-history',data.bookings,'No pickups linked to this email yet.',b=>b.pickup_date+' · '+b.pickup_time+' · '+b.confirmation_number+' · '+b.status+' · '+(b.items||''));list('#points-activity',data.activity,'Your points will appear after your first completed, paid pickup.',r=>(r.points>0?'+':'')+r.points+' · '+r.description);list('#reward-requests',data.requests,'No reward requests yet.',r=>r.tier+'% off · '+r.status)}catch(e){status.textContent='Please sign in again. '+e.message;$('#member-panel').hidden=true;$('#signin-panel').hidden=false}}
$('#signin-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/auth/v1/otp?redirect_to='+encodeURIComponent(location.origin+'/account.html'),{email:$('#member-email').value.trim(),create_user:true});status.textContent='Check your email for your secure sign-in link.'}catch(e){status.textContent=e.message}finally{button.disabled=false}});
$('#signout').addEventListener('click',async()=>{try{await api('/auth/v1/logout',{},session.token)}catch{}sessionStorage.removeItem('bryanMember');location.replace('account.html')});
if(session?.token)dashboard();
})();
