'use strict';
const header=document.querySelector('header');const nav=document.querySelector('nav');if(header&&nav&&!document.querySelector('#menu-toggle')){const menu=document.createElement('button');menu.id='menu-toggle';menu.className='menu-toggle';menu.type='button';menu.setAttribute('aria-label','Open menu');menu.setAttribute('aria-expanded','false');menu.innerHTML='<span></span><span></span><span></span>';header.insertBefore(menu,nav);menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')})}
const footerArea=[...document.querySelectorAll('footer span')].find(x=>/Serving SGV/i.test(x.textContent));if(footerArea){footerArea.innerHTML='<a href="san-gabriel-valley.html">SGV</a> · <a href="los-angeles.html">LA</a> · <a href="inland-empire.html">IE</a> · <a href="riverside.html">Riverside</a> · <a href="orange-county.html">OC</a>'}
const calculator=document.querySelector('#calculator');
if(calculator){
 const result=document.querySelector('#price-result');
 calculator.querySelectorAll('#home-size input').forEach(input=>input.disabled=true);
 calculator.addEventListener('change',()=>{const home=document.querySelector('#home-size');home.hidden=new FormData(calculator).get('load')!=='home';home.querySelectorAll('input').forEach(input=>input.disabled=home.hidden);result.hidden=true});
 calculator.addEventListener('submit',e=>{
  e.preventDefault();const data=Object.fromEntries(new FormData(calculator));const price=estimatePickup(data);
  document.querySelector('#price-value').textContent=price.low===null?'Let’s review your pickup':price.low===price.high?'$'+price.low:'$'+price.low+'–$'+price.high;
  document.querySelector('#price-note').textContent=price.note;
  const saved={...data,price};delete saved.photos;
  sessionStorage.setItem('pickupEstimate',JSON.stringify(saved));
  const query=new URLSearchParams({city:data.city,area:data.area});document.querySelector('#reserve-estimate').href='schedule.html?'+query;
  result.hidden=false;result.focus();result.scrollIntoView({behavior:'smooth',block:'center'});
 });
 document.querySelector('#edit-estimate').addEventListener('click',()=>{result.hidden=true;calculator.scrollIntoView({behavior:'smooth'})});
}
const booking=document.querySelector('#booking');
if(booking){
 const hourButtons=[...document.querySelectorAll('[data-hour]')];const refreshPast=()=>{const today=new Date();const selected=selectedDate===today.toISOString().slice(0,10);hourButtons.forEach(b=>{b.disabled=selected && Number(b.dataset.hour)<=today.getHours()})};const monthLabel=document.querySelector('#calendar-month'),days=document.querySelector('#calendar-days');let cursor=new Date();cursor.setDate(1);let selectedDate='',selectedTime='';
 const render=()=>{const y=cursor.getFullYear(),m=cursor.getMonth();monthLabel.textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor);days.innerHTML='';const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)days.append(document.createElement('span'));for(let n=1;n<=last;n++){const b=document.createElement('button');b.type='button';b.textContent=n;b.dataset.date=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;const nowDate=new Date();const todayDate=new Date(nowDate.getFullYear(),nowDate.getMonth(),nowDate.getDate());const cellDate=new Date(y,m,n);if(cellDate<todayDate){b.disabled=true;b.classList.add('past')}b.addEventListener('click',()=>{if(b.disabled)return;selectedDate=b.dataset.date;days.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');refreshPast()});days.append(b)}};
 refreshPast();document.querySelector('[data-calendar-prev]').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1);render();refreshPast()});document.querySelector('[data-calendar-next]').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1);render();refreshPast()});document.querySelectorAll('[data-hour]').forEach(b=>b.addEventListener('click',()=>{selectedTime=b.textContent;document.querySelectorAll('[data-hour]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
 booking.addEventListener('submit',e=>{e.preventDefault();if(!selectedDate||!selectedTime){alert('Choose a day and arrival window first.');return}const d=new FormData(booking);const summary=`${selectedDate} at ${selectedTime} · ${d.get('city')} · ${d.get('name')}`;document.querySelector('#booking-summary').textContent=summary;document.querySelector('#booking-result').hidden=false;document.querySelector('#booking-text').href='sms:+16263865623?body='+encodeURIComponent(`Hi Bryan! I’d like to book ${summary}. Items: ${d.get('items')}. I’ll attach photos.`);if(!document.querySelector('#confirmation-link')){const a=document.createElement('a');a.id='confirmation-link';a.className='text-link';a.href='confirmation.html';a.textContent='See confirmation page ↗';document.querySelector('#booking-result').append(a)}});render();
}
if(calculator && location.pathname.endsWith('estimate-survey.html')){const steps=[...calculator.querySelectorAll('fieldset')];let current=0;const nav=document.createElement('div');nav.className='survey-nav';const back=document.createElement('button');back.type='button';back.className='reset';back.textContent='Back';const next=document.createElement('button');next.type='button';next.className='button';next.textContent='Next question ↗';nav.append(back,next);calculator.insertBefore(nav,calculator.querySelector('button[type=submit]'));const paint=()=>{steps.forEach((s,i)=>s.hidden=i!==current);back.hidden=current===0;next.hidden=current===steps.length-1;calculator.querySelector('button[type=submit]').hidden=current!==steps.length-1};next.addEventListener('click',()=>{const fields=[...steps[current].querySelectorAll('input,select,textarea')];if(fields.some(f=>!f.checkValidity())){fields.find(f=>!f.checkValidity())?.reportValidity();return}current++;paint()});back.addEventListener('click',()=>{current--;paint()});paint()}
if(booking){booking.addEventListener('submit',async()=>{const d=new FormData(booking);const payload={contact_name:d.get('name'),phone:d.get('phone'),email:d.get('email'),address:d.get('address'),city:d.get('city'),pickup_date:selectedDate,pickup_time:selectedTime,items:d.get('items'),payment_preference:d.get('payment')};try{const res=await fetch('https://qcscbkzpfvrbmtvhubtg.supabase.co/functions/v1/create-booking',{method:'POST',headers:{'Content-Type':'application/json','apikey':'sb_publishable_qKdJB3Kch41AtT5-AI73Mg_0MJyateY'},body:JSON.stringify(payload)});const out=await res.json();if(res.ok){const a=document.querySelector('#confirmation-link');if(a)a.href='confirmation.html?confirmation='+encodeURIComponent(out.confirmation_number);const n=document.querySelector('#booking-summary');if(n)n.textContent+=' · Confirmation '+out.confirmation_number}else{alert(out.error||'That time is no longer available.')}}catch(_){/* keep text fallback available */}})}
