'use strict';
const bookingPublicToken='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjc2Nia3pwZnZyYm10dmh1YnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNTkyNzUsImV4cCI6MjEwNDkzNTI3NX0.N_Hb3jNZ2WvMpCTie3jl3qRdjZNj8suW4NfppOd29lU';
const header=document.querySelector('header');const nav=document.querySelector('nav');if(header&&nav&&!document.querySelector('#menu-toggle')){const menu=document.createElement('button');menu.id='menu-toggle';menu.className='menu-toggle';menu.type='button';menu.setAttribute('aria-label','Open menu');menu.setAttribute('aria-expanded','false');menu.innerHTML='<span></span><span></span><span></span>';header.insertBefore(menu,nav);menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')})}
const footerArea=[...document.querySelectorAll('footer span')].find(x=>/Serving SGV/i.test(x.textContent));if(footerArea){footerArea.innerHTML='<a href="san-gabriel-valley.html">SGV</a> · <a href="los-angeles.html">LA</a> · <a href="inland-empire.html">IE</a> · <a href="riverside.html">Riverside</a> · <a href="orange-county.html">OC</a>'}
document.querySelectorAll('.city-toggle').forEach(button=>button.addEventListener('click',()=>{const list=document.getElementById(button.getAttribute('aria-controls'));const open=list.hasAttribute('open');list.toggleAttribute('open',!open);button.setAttribute('aria-expanded',String(!open));if(!open)list.scrollIntoView({behavior:'smooth',block:'nearest'})}));
const calculator=document.querySelector('#calculator');
if(calculator){
 const result=document.querySelector('#price-result');
 calculator.addEventListener('change',()=>{const rough=document.querySelector('#rough-size');if(rough){rough.hidden=new FormData(calculator).get('load')!=='unknown';rough.querySelectorAll('input').forEach(x=>x.disabled=rough.hidden)}});
 calculator.querySelectorAll('#home-size input').forEach(input=>input.disabled=true);
 const otherWrap=document.querySelector('#other-item-wrap');const otherInput=document.querySelector('#other-item');calculator.addEventListener('change',()=>{const show=new FormData(calculator).get('itemType')==='other';if(otherWrap)otherWrap.hidden=!show;if(otherInput){otherInput.disabled=!show;otherInput.required=show}});if(otherInput)otherInput.disabled=true;
 calculator.addEventListener('change',()=>{const home=document.querySelector('#home-size');home.hidden=new FormData(calculator).get('load')!=='home';home.querySelectorAll('input').forEach(input=>input.disabled=home.hidden);result.hidden=true});
 calculator.addEventListener('submit',e=>{
  e.preventDefault();const data=Object.fromEntries(new FormData(calculator));const price=estimatePickup(data);
  document.querySelector('#price-value').textContent=price.low===null?'Let’s review your pickup':price.low===price.high?'$'+price.low:'$'+price.low+'–$'+price.high;
  document.querySelector('#price-note').textContent=price.note;
  const saved={...data,price};delete saved.photos;
  sessionStorage.setItem('pickupEstimate',JSON.stringify(saved));
  const query=new URLSearchParams({city:data.city,area:data.area});document.querySelector('#reserve-estimate').href='schedule.html?'+query;
  result.hidden=false;result.focus();result.scrollIntoView({behavior:'smooth',block:'center'});
 });
 document.querySelector('#edit-estimate').addEventListener('click',()=>{result.hidden=true;calculator.scrollIntoView({behavior:'smooth'})});
}
const booking=document.querySelector('#booking');
let pendingBooking=null;
if(booking){
 const hourButtons=[...document.querySelectorAll('[data-hour]')];const refreshPast=()=>{const today=new Date();const selected=selectedDate===today.toISOString().slice(0,10);hourButtons.forEach(b=>{b.disabled=selected && Number(b.dataset.hour)<=today.getHours()})};const monthLabel=document.querySelector('#calendar-month'),days=document.querySelector('#calendar-days');let cursor=new Date();cursor.setDate(1);let selectedDate='',selectedTime='';
 const render=()=>{const y=cursor.getFullYear(),m=cursor.getMonth();monthLabel.textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor);days.innerHTML='';const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)days.append(document.createElement('span'));for(let n=1;n<=last;n++){const b=document.createElement('button');b.type='button';b.textContent=n;b.dataset.date=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;const nowDate=new Date();const todayDate=new Date(nowDate.getFullYear(),nowDate.getMonth(),nowDate.getDate());const cellDate=new Date(y,m,n);if(cellDate<todayDate){b.disabled=true;b.classList.add('past')}b.addEventListener('click',()=>{if(b.disabled)return;selectedDate=b.dataset.date;days.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');refreshPast()});days.append(b)}};
 refreshPast();document.querySelector('[data-calendar-prev]').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1);render();refreshPast()});document.querySelector('[data-calendar-next]').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1);render();refreshPast()});document.querySelectorAll('[data-hour]').forEach(b=>b.addEventListener('click',()=>{selectedTime=b.textContent;document.querySelectorAll('[data-hour]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
 let bookedTimes=[];let availabilityReady=false;
 const api='https://qcscbkzpfvrbmtvhubtg.supabase.co/functions/v1/create-booking';
 const key='sb_publishable_qKdJB3Kch41AtT5-AI73Mg_0MJyateY';
 const checkAvailability=async()=>{const date=selectedDate;availabilityReady=false;hourButtons.forEach(x=>x.disabled=true);try{const res=await fetch(api+'?date='+date,{headers:{apikey:key,Authorization:"Bearer "+bookingPublicToken}});const out=await res.json();if(!res.ok)throw Error();if(date!==selectedDate)return;bookedTimes=out.times;availabilityReady=true;refreshPast();hourButtons.forEach(x=>{if(bookedTimes.includes(x.textContent))x.disabled=true});}catch{alert('Availability could not be checked. Please try selecting the day again.')}};
 days.addEventListener('click',e=>{if(e.target.dataset.date&&!e.target.disabled){selectedTime='';hourButtons.forEach(x=>x.classList.remove('selected'));checkAvailability()}});
 const params=new URLSearchParams(location.search);if(params.get('city'))booking.elements.city.value=params.get('city');
 const bookingResult=document.querySelector('#booking-result');
 const details=document.querySelector('#booking-details');
 booking.addEventListener('input',()=>{pendingBooking=null;bookingResult.hidden=true});
 booking.addEventListener('submit',e=>{e.preventDefault();if(!availabilityReady||!selectedDate||!selectedTime){alert('Choose a day and arrival window first.');return}pendingBooking=new FormData(booking);const escape=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const d=Object.fromEntries([...pendingBooking].map(([k,v])=>[k,escape(v)]));pendingBooking.set('pickup_date',selectedDate);pendingBooking.set('pickup_time',selectedTime);details.innerHTML=`<p><strong>${selectedDate} at ${selectedTime}</strong></p><dl><dt>Name</dt><dd>${d.name}</dd><dt>City or ZIP</dt><dd>${d.city}</dd><dt>Phone</dt><dd>${d.phone}</dd><dt>Email</dt><dd>${d.email}</dd><dt>Pickup address</dt><dd>${d.address}</dd><dt>Payment</dt><dd>${d.payment}</dd><dt>Items</dt><dd>${d.items}</dd></dl>`;bookingResult.hidden=false;bookingResult.scrollIntoView({behavior:'smooth',block:'center'});});
 document.querySelector('#edit-booking').addEventListener('click',()=>{pendingBooking=null;bookingResult.hidden=true;booking.scrollIntoView({behavior:'smooth',block:'center'})});
 document.querySelector('#confirm-booking').addEventListener('click',()=>booking.dispatchEvent(new Event('confirmed')));
 render();
}
if(booking){booking.addEventListener('confirmed',async()=>{if(!pendingBooking)return;const button=document.querySelector('#confirm-booking');if(button.disabled)return;button.disabled=true;button.textContent='Confirming…';const d=pendingBooking;const payload={contact_name:d.get('name'),phone:d.get('phone'),email:d.get('email'),address:d.get('address'),city:d.get('city'),pickup_date:d.get('pickup_date'),pickup_time:d.get('pickup_time'),items:d.get('items'),payment_preference:d.get('payment')};try{const res=await fetch('https://qcscbkzpfvrbmtvhubtg.supabase.co/functions/v1/create-booking',{method:'POST',headers:{Authorization:'Bearer '+bookingPublicToken,'Content-Type':'application/json','apikey':'sb_publishable_qKdJB3Kch41AtT5-AI73Mg_0MJyateY'},body:JSON.stringify(payload)});const out=await res.json();if(res.ok){sessionStorage.setItem('confirmedBooking',JSON.stringify({...payload,confirmation_number:out.confirmation_number}));window.location.href='confirmation.html?confirmation='+encodeURIComponent(out.confirmation_number)}else{alert(out.error||'That time is no longer available.')}}catch(_){alert('We could not confirm your reservation. Please call 626-386-5623 before retrying.')}finally{button.disabled=false;button.textContent='Confirm details ↗'}})}
