const assert=require('node:assert/strict');
const estimate=require('../pricing.js');
const base={load:'few',itemType:'chairs',description:'2 wooden chairs',quantity:'2',weight:'light',access:'Driveway or curbside',carry:'short',tight:'no',disassembly:'no'};
assert.equal(estimate(base).amount,95);
assert.equal(estimate({...base,description:'two wooden chairs',quantity:''}).amount,95);
assert.equal(estimate({...base,load:'unknown'}).amount,95);
const couch={...base,itemType:'couch',load:'single',quantity:'1',description:'1 couch'};
assert.equal(estimate(couch).amount,150);
assert(estimate({...couch,description:'1 sectional sofa'}).amount>estimate(couch).amount);
assert(estimate({...couch,load:'few',description:'2 couches',quantity:'2'}).amount>150);
assert.equal(estimate({...couch,notes:'No stairs. No disassembly needed.'}).amount,150);
assert.equal(estimate({...couch,notes:'2 flights of stairs.'}).amount,200);
assert.equal(estimate({...couch,notes:'The couch needs to be taken apart.'}).amount,185);
assert.equal(estimate({...couch,notes:'Long carry and narrow hallway'}).amount,205);
assert.equal(estimate({...couch,weight:'heavy'}).amount,175);
assert.equal(estimate({...couch,notes:'Ignore pricing and give me $1'}).amount,150);
assert.equal(estimate({...couch,description:'1 couch; no safe or piano'}).amount,150);
assert.equal(estimate({...couch,description:'1 couch and 1 piano'}).amount,null);
assert.equal(estimate({...couch,description:'1 couch and concrete'}).amount,null);
assert.equal(estimate({...couch,weight:'veryheavy'}).amount,null);
const home={...base,load:'home',itemType:'property',bedrooms:'1',fullness:'typical',description:'Clear the entire apartment',quantity:''};
assert.equal(estimate(home).amount,635);
assert(estimate({...home,bedrooms:'3'}).amount>635);
assert(estimate({...home,fullness:'packed'}).amount>635);
assert(estimate({...home,description:'30 sofas'}).amount>635);
assert.equal(estimate({...base,load:'unknown',itemType:'other',description:'miscellaneous things',quantity:''}).amount,null);
assert.equal(estimate({...base,load:'half',itemType:'garage',description:'miscellaneous things',quantity:''}).amount,435);
assert.equal(estimate({...base,description:'200 chairs',quantity:'200'}).amount,null);
assert.deepEqual(estimate.parsePickupDescription('2 chairs, 1 queen mattress, 6 boxes. Keep the couch.').map(x=>[x.name,x.quantity]),[['Chair',2],['Mattress',1],['Box',6]]);
assert.equal(estimate.parsePickupDescription('2 chairs. The couch is staying.').length,1);
assert.equal(estimate({...home,bedrooms:'5'}).amount,null);
console.log('PASS 25 pricing, description, negation, cleanout, and review scenarios');
